# Title: Blog

# Jekyll plugins that are supported by GitHub pages
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Also render the README to HTML even if there is an index.md
include:
  - README.md

# Exclude the `vendor` folder created by Travis
exclude:
  - vendor

# Use the Foundation For Public Code Jekyll theme
remote_theme: publiccodenet/jekyll-theme

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"